!!python/object/apply:collections.OrderedDict
- - - version
    - [0, 19, 1]
  - - scalers
    - diffraction_peaks:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - &id001 !!python/name:numpy.ndarray ''
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - &id002 !!python/object/apply:numpy.dtype
            args: [f8, 0, 1]
            state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
          - false
          - !!binary |
            6hz5jxCaN0Ck39Lgt1n4P2gTtOTsIHY/2b3ZibowNEBdw+UbX5QKQHKjN9g6Rbo/BiBsuBmWYD/n
            vjWivBjAP9J1QpTGz9y/cRNToiIj4L908KVSQnbbv7fiFMYi796/NHhWO+bH4D8=
        n_samples_seen_: 1784
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            p79zixVZNUDrOQTLfnDnP/pkf1tapH0/bRwSV14VQUCr8cRsQCDvP6xaIAagtps/PbfTlwtCQz89
            7hSkAOi0P6RAauxElyNAjGoNlZl6yz878ZbzGRTLPxxT1LktE8s/2xwijiIfzD8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            mUHcjch7fEChlFm9QSvhP4Pk/+QvdQs/4UzXAoU9kkCl0hhUnUbuP06GvElAAEg/PMxDKOwtlz4p
            ucqsJVF7PzeWk9fZ/FdAIEZ44biYpz+bP5Rr+OmmPz9PJKho6KY/F2XUw5q2qD8=
        with_mean: true
        with_std: true
      guinier_porod:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            6hz5jxCaN0Ck39Lgt1n4P2gTtOTsIHY/2b3ZibowNEBdw+UbX5QKQHKjN9g6Rbo/BiBsuBmWYD/n
            vjWivBjAP9J1QpTGz9y/cRNToiIj4L908KVSQnbbv7fiFMYi796/NHhWO+bH4D8=
        n_samples_seen_: 1784
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            p79zixVZNUDrOQTLfnDnP/pkf1tapH0/bRwSV14VQUCr8cRsQCDvP6xaIAagtps/PbfTlwtCQz89
            7hSkAOi0P6RAauxElyNAjGoNlZl6yz878ZbzGRTLPxxT1LktE8s/2xwijiIfzD8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            mUHcjch7fEChlFm9QSvhP4Pk/+QvdQs/4UzXAoU9kkCl0hhUnUbuP06GvElAAEg/PMxDKOwtlz4p
            ucqsJVF7PzeWk9fZ/FdAIEZ44biYpz+bP5Rr+OmmPz9PJKho6KY/F2XUw5q2qD8=
        with_mean: true
        with_std: true
      spherical_normal:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            6hz5jxCaN0Ck39Lgt1n4P2gTtOTsIHY/2b3ZibowNEBdw+UbX5QKQHKjN9g6Rbo/BiBsuBmWYD/n
            vjWivBjAP9J1QpTGz9y/cRNToiIj4L908KVSQnbbv7fiFMYi796/NHhWO+bH4D8=
        n_samples_seen_: 1784
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            p79zixVZNUDrOQTLfnDnP/pkf1tapH0/bRwSV14VQUCr8cRsQCDvP6xaIAagtps/PbfTlwtCQz89
            7hSkAOi0P6RAauxElyNAjGoNlZl6yz878ZbzGRTLPxxT1LktE8s/2xwijiIfzD8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            mUHcjch7fEChlFm9QSvhP4Pk/+QvdQs/4UzXAoU9kkCl0hhUnUbuP06GvElAAEg/PMxDKOwtlz4p
            ucqsJVF7PzeWk9fZ/FdAIEZ44biYpz+bP5Rr+OmmPz9PJKho6KY/F2XUw5q2qD8=
        with_mean: true
        with_std: true
      unidentified:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            7oLQX3HHNUBLtBfWrj74P58NFRPCKXw/EUYq2Do/M0BZOyNt+nQKQOp8mmKfR7s/8MRKQRZ0YD/F
            QTehTlXCP8yJNwnPBNi/R91tOw8U2782w1LtxznXv5vlA+htBNq/X7r9Vd8Z3D8=
        n_samples_seen_: 1946
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            y3Hbe9lRNUCksMwX+JjnP87cpyh9foM/lF7Y0T91QEBIb7yZDbryPx/HZyhTCp8/WNb56DneQj+d
            SwN+zPG4Pykt7sSAxiJAsVip2bqg1j8qhM6IGAHUP7oGnZvSxNU/SjlhTjSF1z8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            80uymn1ofEBwx5vev2bhP+QLojdRwBc/2EgM2trtkEAU5ykWEuv1P3VsGnMEHE4/dtAE1BBAlj6p
            y0nS1XGDP9RELnJACFZAhH8MPCgAwD83AztpvQK5P5HzNAsenr0/A8rMq6VJwT8=
        with_mean: true
        with_std: true
  - - models
    - diffraction_peaks:
        C: 1.0
        _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id002
          - false
          - !!binary |
            AAAAAAAA8D8AAAAAAADwPw==
        _max_iter: 5
        _tol: null
        alpha: 0.0001
        average: false
        class_weight: null
        classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - &id003 !!python/object/apply:numpy.dtype
            args: [i8, 0, 1]
            state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
          - false
          - !!binary |
            AAAAAAAAAAABAAAAAAAAAA==
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1, 13]
          - *id002
          - false
          - !!binary |
            H3p8tUhXMkBkzvsbxXceQFtd0ICjzuW/d3vsCw+kNUB+/2twO1oDwAGKb8f4ATrAYz6f+KqxLsDE
            3NNm69IFwItd9wo6JgpAkscvklND87/ByvuC4xoHQDqfQl+j38E/mN0Pr8kxA0A=
        epsilon: 0.1
        eta0: 0.0
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            ejLM/NeAGkA=
        l1_ratio: 0.15
        learning_rate: optimal
        loss: log
        loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
        max_iter: null
        n_iter: null
        n_iter_: 5
        n_jobs: 1
        penalty: l2
        power_t: 0.5
        random_state: null
        shuffle: true
        t_: 8921.0
        tol: null
        verbose: 0
        warm_start: false
      guinier_porod:
        C: 1.0
        _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id002
          - false
          - !!binary |
            AAAAAAAA8D8AAAAAAADwPw==
        _max_iter: 5
        _tol: null
        alpha: 0.1
        average: false
        class_weight: null
        classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id003
          - false
          - !!binary |
            AAAAAAAAAAABAAAAAAAAAA==
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1, 13]
          - *id002
          - false
          - !!binary |
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAX
            hz0qyMjyPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
        epsilon: 0.1
        eta0: 0.0
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            mjIqAi0S3r8=
        l1_ratio: 1.0
        learning_rate: optimal
        loss: log
        loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
        max_iter: null
        n_iter: null
        n_iter_: 5
        n_jobs: 1
        penalty: elasticnet
        power_t: 0.5
        random_state: null
        shuffle: true
        t_: 8921.0
        tol: null
        verbose: 0
        warm_start: false
      spherical_normal:
        C: 1.0
        _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id002
          - false
          - !!binary |
            AAAAAAAA8D8AAAAAAADwPw==
        _max_iter: 5
        _tol: null
        alpha: 0.01
        average: false
        class_weight: null
        classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id003
          - false
          - !!binary |
            AAAAAAAAAAABAAAAAAAAAA==
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1, 13]
          - *id002
          - false
          - !!binary |
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF1qoySnkOa/AAAAAAAAAABL
            HyTodbwJwAAAAAAAAAAAAAAAAAAAAADeE2ZGR0PpPwAAAAAAAAAAAAAAAAAAAAA=
        epsilon: 0.1
        eta0: 0.0
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            uEISpKJNEEA=
        l1_ratio: 0
        learning_rate: optimal
        loss: log
        loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
        max_iter: null
        n_iter: null
        n_iter_: 5
        n_jobs: 1
        penalty: l1
        power_t: 0.5
        random_state: null
        shuffle: true
        t_: 8921.0
        tol: null
        verbose: 0
        warm_start: false
      unidentified:
        C: 1.0
        _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id002
          - false
          - !!binary |
            AAAAAAAA8D8AAAAAAADwPw==
        _max_iter: 5
        _tol: null
        alpha: 0.01
        average: false
        class_weight: null
        classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id003
          - false
          - !!binary |
            AAAAAAAAAAABAAAAAAAAAA==
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1, 13]
          - *id002
          - false
          - !!binary |
            AAAAAAAAAAAAAAAAAAAAAGlXZhUXOuI/AAAAAAAAAAAAAAAAAAAAAMrNS2anBec/AAAAAAAAAACc
            vGnYhTvWPwAAAAAAAAAAFkepZVs24D9mQy84tOXlP16DtfrPVOI/ZdGp89Z13L8=
        epsilon: 0.1
        eta0: 0.0
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            XbFb/5k7FsA=
        l1_ratio: 0.5
        learning_rate: optimal
        loss: log
        loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
        max_iter: null
        n_iter: null
        n_iter_: 5
        n_jobs: 1
        penalty: elasticnet
        power_t: 0.5
        random_state: null
        shuffle: true
        t_: 9731.0
        tol: null
        verbose: 0
        warm_start: false
  - - accuracy
    - diffraction_peaks: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        aQAon1Ef7z8=
      guinier_porod: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        LsjMBLlI6j8=
      spherical_normal: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        PG8FBYem7z8=
      unidentified: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        SgKmW16U7z8=
