!!python/object/apply:collections.OrderedDict
- - - version
    - [0, 19, 1]
  - - scalers
    - r0_sphere:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - &id001 !!python/name:numpy.ndarray ''
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - &id002 !!python/object/apply:numpy.dtype
            args: [f8, 0, 1]
            state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
          - false
          - !!binary |
            gvJny2RZKECRy4cJOWfwPxGyB6spTVs/Ivafp5KaEECTStCb7A8GQEgYItQZYbo/DcsYtFbSYD+y
            QcrXNZC1P0qdZN3Ftd6/i3NRj9JF478QGCwVnpzdv5mH3fx+9uG/7XZReDST5D8=
        n_samples_seen_: 382
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            0f0i4zxyEUCCwulba5qdPzSBEHAExWE/gXIic8M8/T/jOChgdyXRP4Cp/Oe5HnM/RTvutk2zNz8F
            QuyK0m2ZP85C6A/QC/o/av1khsiguD+RzqYEV0O3P4xh1zbaPrg/2QxdUfDFuD8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            G8I2B/EFM0AvilTBy2JLPxXka2sjvNM+ivVHopW2CkCB2+xn9V+yP+EXjog02fY+2rohZayNgT5h
            0szgETVEPxArLXY2MwVAKADAo1T0gj+95P/LWumAP4Ggp8XCXoI/NiIC2LAtgz8=
        with_mean: true
        with_std: true
      rg_gp:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [16]
          - *id002
          - false
          - !!binary |
            BfZxE0sWFUAxs+YaHRHyP5f8TGDp/oY/yZFp4iKqJUA2kEbE6GQJQPSmX8F0pcA/AZt+6Y2tZT+d
            TWmfrdnKP/At9BxfUck/vlbhw6iu579XB+n89xfmvyepqCC9Uee/vOO9n5v65z8jxSU7+PZvQHR1
            01Oy1OA/A3mqZZTTxj8=
        n_samples_seen_: 285
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [16]
          - *id002
          - false
          - !!binary |
            3fbeYXJ3BEDXcjzT1qe3PxNVSnbh/oA/dhn+FmkPGUCqgzD2ZvHtP3JNWxqorJI/ci33/dZTUz9F
            6Gtp10myP/VNWDutMuo/+zJTKdXXzD+HHaRMuiHLP6HLPG2/Ecw/d8Cj7ymhzT/T05PEatiAQCux
            Tz2oqt8/v7x3N0AjuT8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [16]
          - *id002
          - false
          - !!binary |
            wfJOrRkuGkC+2oUftXyBP4l0aS+fDRI/9LTLnxugQ0A+cl+2pwTsP+pCamDByzU/usn+7NVYtz4u
            5yh2eed0P7q8csGpcuU/jtU4xmT/qT/8n8/tDQGnP2yWB9cYn6g/ryGLsEdvqz8TtavORLwRQTha
            yhU0Vs8/FkulKzu/gz8=
        with_mean: true
        with_std: true
      sigma_sphere:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [17]
          - *id002
          - false
          - !!binary |
            gvJny2RZKECRy4cJOWfwPxGyB6spTVs/Ivafp5KaEECTStCb7A8GQEgYItQZYbo/DcsYtFbSYD+y
            QcrXNZC1P0qdZN3Ftd6/i3NRj9JF478QGCwVnpzdv5mH3fx+9uG/7XZReDST5D8AkC5/NZnHP8aL
            4yDDCpU/2v4juPpuzT8D7BM0ad+5Pw==
        n_samples_seen_: 382
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [17]
          - *id002
          - false
          - !!binary |
            0f0i4zxyEUCCwulba5qdPzSBEHAExWE/gXIic8M8/T/jOChgdyXRP4Cp/Oe5HnM/RTvutk2zNz8F
            QuyK0m2ZP85C6A/QC/o/av1khsiguD+RzqYEV0O3P4xh1zbaPrg/2QxdUfDFuD8YGSdKND6pP2Yq
            YOfTWac/gRDA1q2d6D/A8728xLT4Pw==
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [17]
          - *id002
          - false
          - !!binary |
            G8I2B/EFM0AvilTBy2JLPxXka2sjvNM+ivVHopW2CkCB2+xn9V+yP+EXjog02fY+2rohZayNgT5h
            0szgETVEPxArLXY2MwVAKADAo1T0gj+95P/LWumAP4Ggp8XCXoI/NiIC2LAtgz9i4NGequljP6t9
            zMQcCmE/AbWbt43v4j8H0yFFJBMDQA==
        with_mean: true
        with_std: true
  - - models
    - r0_sphere:
        C: 1.0
        _max_iter: 1000
        _tol: null
        alpha: 0.0001
        average: false
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            LWG1pIctE0D363BGBFDQv5auTJBD2M8/gNy4khw4yT8Qtf9/MMbRv9v7VkPWHty/1m61JFxf4D/x
            e5s5ie7mP+cdhKJNhZM/sWOEURzy8T8rox7wHeDRvwJf+aLhHOY/KA5/Oons+L8=
        epsilon: 0.1
        eta0: 0.01
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            xXzKXAYqOUA=
        l1_ratio: 0.15
        learning_rate: invscaling
        loss: squared_loss
        max_iter: 1000
        n_iter: null
        n_iter_: 1000
        penalty: l2
        power_t: 0.25
        random_state: null
        shuffle: true
        t_: 382001.0
        tol: null
        verbose: 0
        warm_start: false
      rg_gp:
        C: 1.0
        _max_iter: 1000
        _tol: null
        alpha: 0.0001
        average: false
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [16]
          - *id002
          - false
          - !!binary |
            aybj0dGk779/4WxQWg2Lvzs8JEcYh+G/NJdGK4aTqj8GFzvD2o3TvxDWgskJm9c/emV5vOJowD/+
            xKwIowzHv7QhD5F4lKc/O19AYqHQ0r9uK6B9Mb/PP+TT1KYXasK/gCtdGD7y3T/REAskt3LuP+A5
            pv28TNa/RLawlcjhy78=
        epsilon: 0.1
        eta0: 0.01
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            kExv4ZAJEUA=
        l1_ratio: 0.15
        learning_rate: invscaling
        loss: squared_loss
        max_iter: 1000
        n_iter: null
        n_iter_: 1000
        penalty: l2
        power_t: 0.25
        random_state: null
        shuffle: true
        t_: 285001.0
        tol: null
        verbose: 0
        warm_start: false
      sigma_sphere:
        C: 1.0
        _max_iter: 1000
        _tol: null
        alpha: 0.0001
        average: false
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [17]
          - *id002
          - false
          - !!binary |
            V6EcHxWXo79iIN7Bc2aXv2JQAtwnuJi/5OErFXmOgr+WUWlQf42LvzWH3MpM768/W2A6BHFMlb9r
            syf9J3x6PyqBpnvYaGk/UrFmdyyJfT+Fg4VaMlaNv055MTnOrRs/lHlOydJRi7/vO2rXrmCGP2kk
            vBVvCki/k4i+iCLRhj8QRtl7g7qPvw==
        epsilon: 0.1
        eta0: 0.01
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            7z3VwHKosT8=
        l1_ratio: 0.15
        learning_rate: invscaling
        loss: squared_loss
        max_iter: 1000
        n_iter: null
        n_iter_: 1000
        penalty: l2
        power_t: 0.25
        random_state: null
        shuffle: true
        t_: 382001.0
        tol: null
        verbose: 0
        warm_start: false
  - - accuracy
    - r0_sphere: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        LIStl5z5uT8=
      rg_gp: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        nTQtnIIn2z8=
      sigma_sphere: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        BEzXEdMM4j8=
