models:
  bad_data:
    C: 1.0
    _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - &id001 !!python/name:numpy.ndarray ''
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [2]
      - &id002 !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - false
      - !!binary |
        AAAAAAAA8D8AAAAAAADwPw==
    _max_iter: 5
    _tol: null
    alpha: 0.001
    average: false
    class_weight: null
    classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [2]
      - *id002
      - false
      - !!binary |
        AAAAAAAAAAAAAAAAAADwPw==
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1, 5]
      - *id002
      - false
      - !!binary |
        b1arSlM/9T8HDIHDHb8fwBJP1nmtcfg/JQ9NDro16T8ttjCgWsmdvw==
    epsilon: 0.1
    eta0: 0.0
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id002
      - false
      - !!binary |
        Bkyl1QR0JMA=
    l1_ratio: 1.0
    learning_rate: optimal
    loss: log
    loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
    max_iter: null
    n_iter: null
    n_iter_: 5
    n_jobs: 1
    penalty: l1
    power_t: 0.5
    random_state: null
    shuffle: true
    t_: 9731.0
    tol: null
    verbose: 0
    warm_start: false
  diffraction_peaks:
    C: 1.0
    _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [2]
      - *id002
      - false
      - !!binary |
        AAAAAAAA8D8AAAAAAADwPw==
    _max_iter: 5
    _tol: null
    alpha: 0.001
    average: false
    class_weight: null
    classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [2]
      - *id002
      - false
      - !!binary |
        AAAAAAAAAAAAAAAAAADwPw==
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1, 5]
      - *id002
      - false
      - !!binary |
        AAAAAAAAAAAYTa3cCC4ZQO3e/dYeCgRAjicSE9Rhyz+pXzOkVdjlvw==
    epsilon: 0.1
    eta0: 0.0
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id002
      - false
      - !!binary |
        HXeN6RcR6j8=
    l1_ratio: 0.85
    learning_rate: optimal
    loss: log
    loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
    max_iter: null
    n_iter: null
    n_iter_: 5
    n_jobs: 1
    penalty: elasticnet
    power_t: 0.5
    random_state: null
    shuffle: true
    t_: 8921.0
    tol: null
    verbose: 0
    warm_start: false
  form_factor_scattering:
    C: 1.0
    _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [2]
      - *id002
      - false
      - !!binary |
        AAAAAAAA8D8AAAAAAADwPw==
    _max_iter: 5
    _tol: null
    alpha: 0.001
    average: false
    class_weight: null
    classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [2]
      - *id002
      - false
      - !!binary |
        AAAAAAAAAAAAAAAAAADwPw==
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1, 5]
      - *id002
      - false
      - !!binary |
        clsH3xPt878prdAX4bM0QAAAAAAAAAAAdO8tyF8ryD/RvflG9172vw==
    epsilon: 0.1
    eta0: 0.0
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id002
      - false
      - !!binary |
        zIR18rNjMEA=
    l1_ratio: 1.0
    learning_rate: optimal
    loss: log
    loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
    max_iter: null
    n_iter: null
    n_iter_: 5
    n_jobs: 1
    penalty: l1
    power_t: 0.5
    random_state: null
    shuffle: true
    t_: 8921.0
    tol: null
    verbose: 0
    warm_start: false
  precursor_scattering:
    C: 1.0
    _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [2]
      - *id002
      - false
      - !!binary |
        AAAAAAAA8D8AAAAAAADwPw==
    _max_iter: 5
    _tol: null
    alpha: 0.01
    average: false
    class_weight: null
    classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [2]
      - *id002
      - false
      - !!binary |
        AAAAAAAAAAAAAAAAAADwPw==
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1, 5]
      - *id002
      - false
      - !!binary |
        hvlEV9Qq3T9gnX9zOTQDwJwDjFnSp/Q/SQw4lSuXuL+MfHubGsjjPw==
    epsilon: 0.1
    eta0: 0.0
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id002
      - false
      - !!binary |
        DHNQ5UyL4r8=
    l1_ratio: 0.85
    learning_rate: optimal
    loss: log
    loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
    max_iter: null
    n_iter: null
    n_iter_: 5
    n_jobs: 1
    penalty: elasticnet
    power_t: 0.5
    random_state: null
    shuffle: true
    t_: 8921.0
    tol: null
    verbose: 0
    warm_start: false
scalers:
  bad_data:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [5]
      - *id002
      - false
      - !!binary |
        jJxh0ZW+tj+rSYhfccc1QKxE59WuPvg/beBXqGuZFUBdG/hs+nQKQA==
    n_samples_seen_: 1946
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [5]
      - *id002
      - false
      - !!binary |
        3tzcaoFKvD/0vqV72VE1QEreyxb4mOc/RUW27k2rCECdwW2ZDbryPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [5]
      - *id002
      - false
      - !!binary |
        /Cac8w8DiT8aMSOafWh8QLIBId2/ZuE/rm+274kEI0CJunEVEuv1Pw==
    with_mean: true
    with_std: true
  diffraction_peaks:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [5]
      - *id002
      - false
      - !!binary |
        56kUyOATsT9GnamPEJo3QFitt+C3Wfg/LihDKaplFEBD+pobX5QKQA==
    n_samples_seen_: 1784
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [5]
      - *id002
      - false
      - !!binary |
        D4q1BQSoqD/FyUCLFVk1QKccOMp+cOc/k6b85POYAUBHmW1sQCDvPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [5]
      - *id002
      - false
      - !!binary |
        rsLMMnj/Yj+xRFSNyHt8QHCPLrxBK+E/nGodb7xaE0BS525TnUbuPw==
    with_mean: true
    with_std: true
  form_factor_scattering:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [5]
      - *id002
      - false
      - !!binary |
        56kUyOATsT9GnamPEJo3QFitt+C3Wfg/LihDKaplFEBD+pobX5QKQA==
    n_samples_seen_: 1784
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [5]
      - *id002
      - false
      - !!binary |
        D4q1BQSoqD/FyUCLFVk1QKccOMp+cOc/k6b85POYAUBHmW1sQCDvPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [5]
      - *id002
      - false
      - !!binary |
        rsLMMnj/Yj+xRFSNyHt8QHCPLrxBK+E/nGodb7xaE0BS525TnUbuPw==
    with_mean: true
    with_std: true
  precursor_scattering:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [5]
      - *id002
      - false
      - !!binary |
        56kUyOATsT9GnamPEJo3QFitt+C3Wfg/LihDKaplFEBD+pobX5QKQA==
    n_samples_seen_: 1784
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [5]
      - *id002
      - false
      - !!binary |
        D4q1BQSoqD/FyUCLFVk1QKccOMp+cOc/k6b85POYAUBHmW1sQCDvPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [5]
      - *id002
      - false
      - !!binary |
        rsLMMnj/Yj+xRFSNyHt8QHCPLrxBK+E/nGodb7xaE0BS525TnUbuPw==
    with_mean: true
    with_std: true
version: [0, 19, 1]
