!!python/object/apply:collections.OrderedDict
- - - version
    - [0, 19, 1]
  - - scalers
    - r0_sphere:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - &id001 !!python/name:numpy.ndarray ''
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - &id002 !!python/object/apply:numpy.dtype
            args: [f8, 0, 1]
            state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
          - false
          - !!binary |
            3QAZbaMKLUDkfNiQ/4HwP4d3wXRys1w/pBPUUMyfEUBfUB2Rp7sGQIJ4egEr0bo/KIP1FYgdYD/X
            xdPrRXq0P4eTGYO/1Oy/jxEcOVQE4r/2CUTm4mzbvxwQzqyVweC/9sn2b+hH4z8=
        n_samples_seen_: 726
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            SJiGc8+NE0AmwI4WJcylP5kidPLun2U/HSfTMRYZA0CCesV52q3TP7LSpXrnRnM/IC2Ew7fJMz+X
            llS7qqmdP/FpI8ZLryVAMHThXf9PuT9SRqODeHO4P/aiyjo9D7k/08ZpQMRcuT8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            ZI41lbXlN0D76EsNDrJdP1kadOcROt0+X/rPC7zLFkBRi2XxRzS4P3voz/mfOfc+3tWokQN5eD4U
            6XIKCX9LP+gXEnOnY11ABbCF/8YFhD9r7Gxx1a6CPyrluO3Wn4M/czzLkf8ZhD8=
        with_mean: true
        with_std: true
      rg_gp:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [16]
          - *id002
          - false
          - !!binary |
            OD+0+v9LEEBeZ1cyhbnyP9t19vhIoYw/Cgb7pBDnJ0ASlrVlU+sLQDBJeT320MA/474tU/rZYj/a
            GP+J0gfOPzBJUe39DuK/DVdkIhIG5b+W0oQ4BgHlv6AulIhfJOW/ckqfZYTR5D9Ercqn0I1iQNe4
            PmGN9Og/J3QsdBeOvz8=
        n_samples_seen_: 518
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [16]
          - *id002
          - false
          - !!binary |
            NVzsuBbyBUDqjWD3dlzaP03TIqzjeYE/HypmJQvkGkB+5yKWXb75PwGGMPdGm5U/s65d1L2dTz+A
            mBoFZNmyPz3GbsFDrilAy2QDCA/Q0j8QdTxz+RLPP3ss0zTvodE/y9XHYKIM1D+eZNt6vBx6QItu
            aH44+OQ/Y2RytXIMuT8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [16]
          - *id002
          - false
          - !!binary |
            1KTmlMoZHkCsmcV/TLfFP1g7/V2kFhM/LdaeO+uYRkCdG/+y3rUEQLttDzl9LT0/0nOPXqk8rz5X
            iPe2qjR2P/0gpN/+m2RAEBrmWLMetj/PUX+PziyuPzcTQDyDbrM/Vaz0658fuT/bqNEVzE4FQYAy
            GxSYe9s/egMmE3ibgz8=
        with_mean: true
        with_std: true
      sigma_sphere:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [17]
          - *id002
          - false
          - !!binary |
            3QAZbaMKLUDkfNiQ/4HwP4d3wXRys1w/pBPUUMyfEUBfUB2Rp7sGQIJ4egEr0bo/KIP1FYgdYD/X
            xdPrRXq0P4eTGYO/1Oy/jxEcOVQE4r/2CUTm4mzbvxwQzqyVweC/9sn2b+hH4z+Hje0pyoXGP4Wm
            rv2KlKs/F7He+M1OyD+nDzV7GSywPw==
        n_samples_seen_: 726
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [17]
          - *id002
          - false
          - !!binary |
            SJiGc8+NE0AmwI4WJcylP5kidPLun2U/HSfTMRYZA0CCesV52q3TP7LSpXrnRnM/IC2Ew7fJMz+X
            llS7qqmdP/FpI8ZLryVAMHThXf9PuT9SRqODeHO4P/aiyjo9D7k/08ZpQMRcuT+4Ry/eqiXZPw/T
            Mwoxx+s/S3hI/5/t4T/qubU5n/TxPw==
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [17]
          - *id002
          - false
          - !!binary |
            ZI41lbXlN0D76EsNDrJdP1kadOcROt0+X/rPC7zLFkBRi2XxRzS4P3voz/mfOfc+3tWokQN5eD4U
            6XIKCX9LP+gXEnOnY11ABbCF/8YFhD9r7Gxx1a6CPyrluO3Wn4M/czzLkf8ZhD8jDNxRB8PDP/1/
            cav6HOg/NbSkGL0W1D+E3TJZbib0Pw==
        with_mean: true
        with_std: true
  - - models
    - r0_sphere:
        C: 1.0
        _max_iter: 1000
        _tol: null
        alpha: 0.0001
        average: false
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - &id003 !!python/object/apply:numpy.dtype
            args: [f8, 0, 1]
            state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
          - false
          - !!binary |
            Pc2P55I/FkBECFccMArnP/lndaqXftI/nh0Q7ze45b+fHTd3ihXSP3DQDF+PM/O/zXSO4I9b5j9+
            r7lmxtH0P1OVDhKmCpy/Mqpvm6w6+j9GNUIrI5b/v2ZdEUV9zN4/F9z9esETBsA=
        epsilon: 0.1
        eta0: 0.01
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            YKcs/ltiPEA=
        l1_ratio: 0.15
        learning_rate: invscaling
        loss: squared_loss
        max_iter: 1000
        n_iter: null
        n_iter_: 1
        penalty: l2
        power_t: 0.25
        random_state: null
        shuffle: true
        t_: 726727.0
        tol: null
        verbose: 0
        warm_start: false
      rg_gp:
        C: 1.0
        _max_iter: 1000
        _tol: null
        alpha: 0.0001
        average: false
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [16]
          - *id003
          - false
          - !!binary |
            WF5dybXp+L80J0tN/sfPP+yEpB2fsfQ/LdnC+g9q2D8L7mIPSqPcv2sg+NUNtvC/87ZtLRl0yL+W
            bFqCPqAQwDFXt00ix94/Lj9nfJdy0L+ow6BbKgIDQNDP1wDj9tg/twqtn0Ol7j+cIsF3rSX/v/YI
            kc3mzPa/DOYCDCLW1D8=
        epsilon: 0.1
        eta0: 0.01
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            NpyzkIg9EkA=
        l1_ratio: 0.15
        learning_rate: invscaling
        loss: squared_loss
        max_iter: 1000
        n_iter: null
        n_iter_: 1
        penalty: l2
        power_t: 0.25
        random_state: null
        shuffle: true
        t_: 518519.0
        tol: null
        verbose: 0
        warm_start: false
      sigma_sphere:
        C: 1.0
        _max_iter: 1000
        _tol: null
        alpha: 0.0001
        average: false
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [17]
          - *id003
          - false
          - !!binary |
            cq5tZdousr8DqK24A5GKv8LN9bd2GaC/8bx95ADRkz9ONe++MM6TvwbmHdD8nKI/ptqYrzU8kb8w
            ZRgX5pCIv0D64hF/IG0/6cVnHCrknT8sPpA1p4q0v4Nmd7qcZHW/4Ypbk9JJsL/6pJM+2Gi3v+Kw
            M4f2i7U/c6+m/Shuer9zSJEQY11nPw==
        epsilon: 0.1
        eta0: 0.01
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            If2BjNq6rj8=
        l1_ratio: 0.15
        learning_rate: invscaling
        loss: squared_loss
        max_iter: 1000
        n_iter: null
        n_iter_: 1
        penalty: l2
        power_t: 0.25
        random_state: null
        shuffle: true
        t_: 726727.0
        tol: null
        verbose: 0
        warm_start: false
  - - accuracy
    - {r0_sphere: Partial fit was used, rg_gp: Partial fit was used, sigma_sphere: Partial
        fit was used}
