!!python/object/apply:collections.OrderedDict
- - - version
    - [0, 19, 1]
  - - scalers
    - diffraction_peaks:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - &id001 !!python/name:numpy.ndarray ''
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - &id002 !!python/object/apply:numpy.dtype
            args: [f8, 0, 1]
            state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
          - false
          - !!binary |
            6hz5jxCaN0Ck39Lgt1n4P2cTtOTsIHY/2b3ZibowNEBcw+UbX5QKQHKjN9g6Rbo/BiBsuBmWYD/n
            vjWivBjAP9B1QpTGz9y/cRNToiIj4L908KVSQnbbv7jiFMYi796/NHhWO+bH4D8=
        n_samples_seen_: 1784
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            p79zixVZNUDrOQTLfnDnP/pkf1tapH0/bRwSV14VQUCr8cRsQCDvP6taIAagtps/PbfTlwtCQz89
            7hSkAOi0P6RAauxElyNAjGoNlZl6yz878ZbzGRTLPxxT1LktE8s/2xwijiIfzD8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            mUHcjch7fEChlFm9QSvhP4Pk/+QvdQs/4UzXAoU9kkCl0hhUnUbuP02GvElAAEg/PcxDKOwtlz4p
            ucqsJVF7PzaWk9fZ/FdAIEZ44biYpz+bP5Rr+OmmPz9PJKho6KY/F2XUw5q2qD8=
        with_mean: true
        with_std: true
      guinier_porod:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            6hz5jxCaN0Ck39Lgt1n4P2cTtOTsIHY/2b3ZibowNEBcw+UbX5QKQHKjN9g6Rbo/BiBsuBmWYD/n
            vjWivBjAP9B1QpTGz9y/cRNToiIj4L908KVSQnbbv7jiFMYi796/NHhWO+bH4D8=
        n_samples_seen_: 1784
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            p79zixVZNUDrOQTLfnDnP/pkf1tapH0/bRwSV14VQUCr8cRsQCDvP6taIAagtps/PbfTlwtCQz89
            7hSkAOi0P6RAauxElyNAjGoNlZl6yz878ZbzGRTLPxxT1LktE8s/2xwijiIfzD8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            mUHcjch7fEChlFm9QSvhP4Pk/+QvdQs/4UzXAoU9kkCl0hhUnUbuP02GvElAAEg/PcxDKOwtlz4p
            ucqsJVF7PzaWk9fZ/FdAIEZ44biYpz+bP5Rr+OmmPz9PJKho6KY/F2XUw5q2qD8=
        with_mean: true
        with_std: true
      spherical_normal:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            6hz5jxCaN0Ck39Lgt1n4P2cTtOTsIHY/2b3ZibowNEBcw+UbX5QKQHKjN9g6Rbo/BiBsuBmWYD/n
            vjWivBjAP9B1QpTGz9y/cRNToiIj4L908KVSQnbbv7jiFMYi796/NHhWO+bH4D8=
        n_samples_seen_: 1784
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            p79zixVZNUDrOQTLfnDnP/pkf1tapH0/bRwSV14VQUCr8cRsQCDvP6taIAagtps/PbfTlwtCQz89
            7hSkAOi0P6RAauxElyNAjGoNlZl6yz878ZbzGRTLPxxT1LktE8s/2xwijiIfzD8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            mUHcjch7fEChlFm9QSvhP4Pk/+QvdQs/4UzXAoU9kkCl0hhUnUbuP02GvElAAEg/PcxDKOwtlz4p
            ucqsJVF7PzaWk9fZ/FdAIEZ44biYpz+bP5Rr+OmmPz9PJKho6KY/F2XUw5q2qD8=
        with_mean: true
        with_std: true
      unidentified:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            7YLQX3HHNUBMtBfWrj74P58NFRPCKXw/EUYq2Do/M0BZOyNt+nQKQOp8mmKfR7s/8MRKQRZ0YD/F
            QTehTlXCP86JNwnPBNi/R91tOw8U2783w1LtxznXv5vlA+htBNq/YLr9Vd8Z3D8=
        n_samples_seen_: 1946
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            y3Hbe9lRNUCjsMwX+JjnP87cpyh9foM/lV7Y0T91QEBIb7yZDbryPx/HZyhTCp8/WNb56DneQj+d
            SwN+zPG4Pykt7sSAxiJAsVip2bqg1j8qhM6IGAHUP7kGnZvSxNU/SjlhTjSF1z8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            80uymn1ofEBvx5vev2bhP+QLojdRwBc/2UgM2trtkEAV5ykWEuv1P3VsGnMEHE4/dtAE1BBAlj6p
            y0nS1XGDP9VELnJACFZAhH8MPCgAwD82AztpvQK5P4/zNAsenr0/AsrMq6VJwT8=
        with_mean: true
        with_std: true
  - - models
    - diffraction_peaks:
        C: 1.0
        _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id002
          - false
          - !!binary |
            AAAAAAAA8D8AAAAAAADwPw==
        _max_iter: 5
        _tol: null
        alpha: 0.0001
        average: false
        class_weight: null
        classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - &id003 !!python/object/apply:numpy.dtype
            args: [i8, 0, 1]
            state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
          - false
          - !!binary |
            AAAAAAAAAAABAAAAAAAAAA==
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1, 13]
          - *id002
          - false
          - !!binary |
            l1io9+70OEAIuuNTgo4XQMN7H24+iOm/B4D7MIz/OUDn1FuzxGAZwJQAXLtJrEDAm9v2Adc+/L94
            c4WsGqgWwBlKUu9sauw/ucOCWPo65L9Cabti8nMTQAAAAAAAAAAANu9t/tptCUA=
        epsilon: 0.1
        eta0: 0.0
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            ocXbXJS0KEA=
        l1_ratio: 0.5
        learning_rate: optimal
        loss: log
        loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
        max_iter: null
        n_iter: null
        n_iter_: 5
        n_jobs: 1
        penalty: elasticnet
        power_t: 0.5
        random_state: null
        shuffle: true
        t_: 8921.0
        tol: null
        verbose: 0
        warm_start: false
      guinier_porod:
        C: 1.0
        _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id002
          - false
          - !!binary |
            AAAAAAAA8D8AAAAAAADwPw==
        _max_iter: 5
        _tol: null
        alpha: 0.1
        average: false
        class_weight: null
        classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id003
          - false
          - !!binary |
            AAAAAAAAAAABAAAAAAAAAA==
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1, 13]
          - *id002
          - false
          - !!binary |
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADL
            BE9RObjyPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
        epsilon: 0.1
        eta0: 0.0
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            6wL3I8TB3b8=
        l1_ratio: 0.15
        learning_rate: optimal
        loss: log
        loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
        max_iter: null
        n_iter: null
        n_iter_: 5
        n_jobs: 1
        penalty: l1
        power_t: 0.5
        random_state: null
        shuffle: true
        t_: 8921.0
        tol: null
        verbose: 0
        warm_start: false
      sperical_normal:
        C: 1.0
        _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id002
          - false
          - !!binary |
            AAAAAAAA8D8AAAAAAADwPw==
        _max_iter: 5
        _tol: null
        alpha: 0.01
        average: false
        class_weight: null
        classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id003
          - false
          - !!binary |
            AAAAAAAAAAABAAAAAAAAAA==
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1, 13]
          - *id002
          - false
          - !!binary |
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABOBEQa8HW6vzXe0hJ4t+q/AAAAAAAAAADM
            CAF85zIGwAAAAAAAAAAAAAAAAAAAAAARPL9VKOPlPwAAAAAAAAAAAAAAAAAAAAA=
        epsilon: 0.1
        eta0: 0.0
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            FvjRSqksDEA=
        l1_ratio: 1.0
        learning_rate: optimal
        loss: log
        loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
        max_iter: null
        n_iter: null
        n_iter_: 5
        n_jobs: 1
        penalty: elasticnet
        power_t: 0.5
        random_state: null
        shuffle: true
        t_: 8921.0
        tol: null
        verbose: 0
        warm_start: false
      unidentified:
        C: 1.0
        _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id002
          - false
          - !!binary |
            AAAAAAAA8D8AAAAAAADwPw==
        _max_iter: 5
        _tol: null
        alpha: 0.1
        average: false
        class_weight: null
        classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id003
          - false
          - !!binary |
            AAAAAAAAAAABAAAAAAAAAA==
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1, 13]
          - *id002
          - false
          - !!binary |
            JBn8zuJWw7+mrZv3XkqLP+16RsO6T9I/W57uXVHIqL9V1zp3mx6Evx0qJpM2ZdA/biIncQWenL+X
            49DVM7nQP9wNlsqNI4U/t0j9IQs61T96g9iKn0LVP6WFuDTcYtU/CYve4c7+1L8=
        epsilon: 0.1
        eta0: 0.0
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            /h7hcxldDcA=
        l1_ratio: 1.0
        learning_rate: optimal
        loss: log
        loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
        max_iter: null
        n_iter: null
        n_iter_: 5
        n_jobs: 1
        penalty: l2
        power_t: 0.5
        random_state: null
        shuffle: true
        t_: 9731.0
        tol: null
        verbose: 0
        warm_start: false
  - - accuracy
    - diffraction_peaks: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        FreqlwtS7z8=
      guinier_porod: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        UATzGzhI6j8=
      spherical_normal: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        nLZPdcKb7z8=
      unidentified: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        KhYBumyi7z8=
