!!python/object/apply:collections.OrderedDict
- - - version
    - [0, 19, 1]
  - - scalers
    - r0_sphere:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - &id001 !!python/name:numpy.ndarray ''
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - &id002 !!python/object/apply:numpy.dtype
            args: [f8, 0, 1]
            state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
          - false
          - !!binary |
            3wAZbaMKLUDkfNiQ/4HwP4d3wXRys1w/oxPUUMyfEUBgUB2Rp7sGQIB4egEr0bo/KIP1FYgdYD/X
            xdPrRXq0P4eTGYO/1Oy/jxEcOVQE4r/4CUTm4mzbvx0QzqyVweC/9sn2b+hH4z8=
        n_samples_seen_: 726
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            SJiGc8+NE0AmwI4WJcylP5gidPLun2U/HCfTMRYZA0CCesV52q3TP7HSpXrnRnM/Hy2Ew7fJMz+X
            llS7qqmdP/FpI8ZLryVAMHThXf9PuT9SRqODeHO4P/aiyjo9D7k/08ZpQMRcuT8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            ZI41lbXlN0D76EsNDrJdP1cadOcROt0+XfrPC7zLFkBRi2XxRzS4P3noz/mfOfc+3dWokQN5eD4U
            6XIKCX9LP+cXEnOnY11ABbCF/8YFhD9r7Gxx1a6CPyrluO3Wn4M/cjzLkf8ZhD8=
        with_mean: true
        with_std: true
      rg_gp:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [20]
          - *id002
          - false
          - !!binary |
            uDcWQapmEECGEAAk6LnyPwFo07sIk4w/J91BkVbLJ0AnCevw87ALQMpTulXJzMA/K6d/qRfjYj8a
            R6V52uzNP905V2mQVeK/eomeMJcz5b+b0UPh0iHlv7iP/wMITuW/lWEW9MAC5T9LGWLhpvTfP709
            yoN1hu0/qqBzgcnU0j/lpadk6pfkP1xovBqFuWJAlIhYeH6a6D9o9Jl+PMO/Pw==
        n_samples_seen_: 513
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [20]
          - *id002
          - false
          - !!binary |
            UIojWzPzBUDnYxJBeXvaP08a92xsf4E/Y3G5hy3eGkAN+BGNuj/5P9qpvHyLnpU/m3B1a568Tz/z
            f6U8gtGyPxWAqp8SzilAavqm4JCD0j9cDmcR3bfOP1HhR530XdE/GctZ0Iy40z/4t+WVbKYPQFMZ
            5iFrkSBAt9rLh8wq9j+nkCsnmOoMQOSqOcKMOXpAu5oz5Bm95D9P8hyE4BS5Pw==
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [20]
          - *id002
          - false
          - !!binary |
            pHnSd9ccHkBWlK13gerFP5esrTO9IhM/P02JlBCPRkC0FDdnEuwDQBHXDi9RNj0/qHSyuMp5rz75
            3QhnHCJ2Pw7yTCksz2RAxDn20j9stT8Jfg/v3nytP4HleIjP2bI/WJxkGp9OuD9RunDq000vQN7y
            X+z/J1FAAxNw8SS2/j+VjpwYQiEqQDbLfDvsfQVB0ytarnvh2j+BmjltrKiDPw==
        with_mean: true
        with_std: true
      sigma_sphere:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [17]
          - *id002
          - false
          - !!binary |
            8d5P3YdKLUAtxVIWZtLwP8L7qxEs21w/T+tFXc7rEkAjITGipr8GQFMHPueW0ro/Gsjpr4sXYD9/
            pTlzx220P72P1/T0f+y/tXqRjNz74b9dcPyOaF3bv4/98H1QueC/8ZT27Ug/4z/kTa0JKGTGPz1u
            D7vyBas/8JU3TIYjyD99EOWzZqavPw==
        n_samples_seen_: 745
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [17]
          - *id002
          - false
          - !!binary |
            Z1xjvd+1E0CbIChp0W/HP7vppiCgXWU/GsIvGk9NCkAoM12LEH3TP0dTYXKkEHM/X+TVMnWRMz84
            9zJ2/1CdP+8nv40vaCVAd6JpPTUMuT+n+SeQWzC4P0CxLgqpy7g/+760anAZuT+Trjht6NPYPxyF
            eEUlbOs/z7suRTiz4T/RCn5mwrnxPw==
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [17]
          - *id002
          - false
          - !!binary |
            cpshxAZIOEA3nE3BQyqhPzVHdDHoh9w+oir/T1ueJUA3BZDd2Ly3P2sUJt+Xt/Y+RttPuKDudz5q
            xIILnNtKP4TT1T4jpFxA97A72Bebgz/UbPJr0kiCP9ktdLuNNoM/JxHs39Ovgz+Fko3rV0PDP1+3
            +2Dsf+c/NCrVDq+U0z+38YfCKaPzPw==
        with_mean: true
        with_std: true
  - - models
    - r0_sphere:
        C: 1.0
        _max_iter: 1000
        _tol: null
        alpha: 0.001
        average: false
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            N2IRPX21FUA5P2ixUj7nP9NAV7uoO9I/+tW2ECuh5b/C0JpEqgDUP+HVMdXKx/K/2F68BiqN5T+W
            uGdoGpn0PwLZxNga1Ze//7tNEze3+T9KYzjDD6r7vzOdUkZHP+E/SxRfpiclBcA=
        epsilon: 1
        eta0: 0.01
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            M7kut1tiPEA=
        l1_ratio: 0.15
        learning_rate: invscaling
        loss: squared_loss
        max_iter: 1000
        n_iter: null
        n_iter_: 1000
        penalty: l2
        power_t: 0.25
        random_state: null
        shuffle: true
        t_: 726001.0
        tol: null
        verbose: 0
        warm_start: false
      rg_gp:
        C: 1.0
        _max_iter: 1000
        _tol: null
        alpha: 0.01
        average: false
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [20]
          - *id002
          - false
          - !!binary |
            AAAAAAAAAAAAAAAAAAAAAKAGJg06RdO/TFO4g7zApD+uIh71ZxLYvwAAAAAAAAAA/Pv4eIlmrz80
            53bbZZKCvwgHx2J3VpI/kcYQ71/X0r8AAAAAAAAAAGkuCPowHGm/fvyVRlLe4z8AAAAAAAAAAD8h
            AnC3FnS/AAAAAAAAAABvds4Z5g9/vxtNac+WsMY/AAAAAAAAAAAHy0irhrvBPw==
        epsilon: 1
        eta0: 0.01
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            V7tELatDDEA=
        l1_ratio: 0.15
        learning_rate: invscaling
        loss: huber
        max_iter: 1000
        n_iter: null
        n_iter_: 1000
        penalty: l1
        power_t: 0.25
        random_state: null
        shuffle: true
        t_: 513001.0
        tol: null
        verbose: 0
        warm_start: false
      sigma_sphere:
        C: 1.0
        _max_iter: 1000
        _tol: null
        alpha: 0.01
        average: false
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [17]
          - *id002
          - false
          - !!binary |
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
        epsilon: 0.01
        eta0: 0.01
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            AHm8obrCqD8=
        l1_ratio: 0.5
        learning_rate: invscaling
        loss: huber
        max_iter: 1000
        n_iter: null
        n_iter_: 1000
        penalty: elasticnet
        power_t: 0.25
        random_state: null
        shuffle: true
        t_: 745001.0
        tol: null
        verbose: 0
        warm_start: false
  - - accuracy
    - r0_sphere: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        6bwG63FOwj8=
      rg_gp: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        gFQ0S0DhzT8=
      sigma_sphere: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        8G9m6m+85D8=
