!!python/object/apply:collections.OrderedDict
- - - version
    - [0, 19, 1]
  - - scalers
    - r0_sphere:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - &id001 !!python/name:numpy.ndarray ''
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - &id002 !!python/object/apply:numpy.dtype
            args: [f8, 0, 1]
            state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
          - false
          - !!binary |
            3wAZbaMKLUDlfNiQ/4HwP4d3wXRys1w/oxPUUMyfEUBfUB2Rp7sGQIJ4egEr0bo/KIP1FYgdYD/X
            xdPrRXq0P4eTGYO/1Oy/jxEcOVQE4r/2CUTm4mzbvxwQzqyVweC/9sn2b+hH4z8=
        n_samples_seen_: 726
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            SJiGc8+NE0AmwI4WJcylP5kidPLun2U/HCfTMRYZA0CCesV52q3TP7LSpXrnRnM/IC2Ew7fJMz+X
            llS7qqmdP/FpI8ZLryVAMHThXf9PuT9SRqODeHO4P/aiyjo9D7k/08ZpQMRcuT8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            ZI41lbXlN0D76EsNDrJdP1kadOcROt0+XPrPC7zLFkBRi2XxRzS4P3voz/mfOfc+3tWokQN5eD4U
            6XIKCX9LP+cXEnOnY11ABbCF/8YFhD9q7Gxx1a6CPyrluO3Wn4M/cjzLkf8ZhD8=
        with_mean: true
        with_std: true
      rg_gp:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [16]
          - *id002
          - false
          - !!binary |
            OD+0+v9LEEBeZ1cyhbnyP9p19vhIoYw/Cgb7pBDnJ0ASlrVlU+sLQDFJeT320MA/474tU/rZYj/a
            GP+J0gfOPy9JUe39DuK/DVdkIhIG5b+W0oQ4BgHlv54ulIhfJOW/ckqfZYTR5D9Ercqn0I1iQNi4
            PmGN9Og/KnQsdBeOvz8=
        n_samples_seen_: 518
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [16]
          - *id002
          - false
          - !!binary |
            NVzsuBbyBUDqjWD3dlzaP07TIqzjeYE/HypmJQvkGkB95yKWXb75PwKGMPdGm5U/sq5d1L2dTz+A
            mBoFZNmyPz/GbsFDrilAy2QDCA/Q0j8RdTxz+RLPP3ss0zTvodE/zNXHYKIM1D+eZNt6vBx6QItu
            aH44+OQ/Y2RytXIMuT8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [16]
          - *id002
          - false
          - !!binary |
            1KTmlMoZHkCsmcV/TLfFP1k7/V2kFhM/LdaeO+uYRkCcG/+y3rUEQLxtDzl9LT0/z3OPXqk8rz5X
            iPe2qjR2P/8gpN/+m2RAEBrmWLMetj/QUX+PziyuPzcTQDyDbrM/Vqz0658fuT/bqNEVzE4FQYAy
            GxSYe9s/egMmE3ibgz8=
        with_mean: true
        with_std: true
      sigma_sphere:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [17]
          - *id002
          - false
          - !!binary |
            895P3YdKLUAtxVIWZtLwP8T7qxEs21w/T+tFXc7rEkAjITGipr8GQFEHPueW0ro/Gsjpr4sXYD9+
            pTlzx220P76P1/T0f+y/tXqRjNz74b9dcPyOaF3bv4/98H1QueC/8ZT27Ug/4z/kTa0JKGTGPz1u
            D7vyBas/8JU3TIYjyD96EOWzZqavPw==
        n_samples_seen_: 745
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [17]
          - *id002
          - false
          - !!binary |
            Z1xjvd+1E0CbIChp0W/HP7vppiCgXWU/GsIvGk9NCkApM12LEH3TP0dTYXKkEHM/X+TVMnWRMz84
            9zJ2/1CdP+8nv40vaCVAd6JpPTUMuT+n+SeQWzC4P0CxLgqpy7g/+760anAZuT+Trjht6NPYPxuF
            eEUlbOs/zrsuRTiz4T/RCn5mwrnxPw==
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [17]
          - *id002
          - false
          - !!binary |
            cpshxAZIOEA3nE3BQyqhPzVHdDHoh9w+oir/T1ueJUA4BZDd2Ly3P2sUJt+Xt/Y+RttPuKDudz5q
            xIILnNtKP4bT1T4jpFxA97A72Bebgz/UbPJr0kiCP9ktdLuNNoM/JxHs39Ovgz+Gko3rV0PDP163
            +2Dsf+c/MyrVDq+U0z+48YfCKaPzPw==
        with_mean: true
        with_std: true
  - - models
    - r0_sphere:
        C: 1.0
        _max_iter: 1000
        _tol: null
        alpha: 0.01
        average: false
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            IPyk1TdUFkBslqfCzP7mP4kqQsHVONI/AHoN7Jib5b8NoL4TBx/SP0M2kXmtPvO/Idyaby505j81
            Nzwkubj0P6GwyBqnvpy/tsjSD9yP+j9aYDe7jU4AwKkJlchvXN4/RzxmGahyBsA=
        epsilon: 1
        eta0: 0.01
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            UncJb1hiPEA=
        l1_ratio: 0.95
        learning_rate: invscaling
        loss: squared_loss
        max_iter: 1000
        n_iter: null
        n_iter_: 1000
        penalty: none
        power_t: 0.25
        random_state: null
        shuffle: true
        t_: 726001.0
        tol: null
        verbose: 0
        warm_start: false
      rg_gp:
        C: 1.0
        _max_iter: 1000
        _tol: null
        alpha: 0.01
        average: false
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [16]
          - *id002
          - false
          - !!binary |
            LjYHAl8jtj8AAAAAAAAAAPIPGcY2ENO/AAAAAAAAAACFv4BXXQnUvwAAAAAAAAAAxjdsmTTfqz9U
            JKtmUHCsvwAAAAAAAAAAIaBBMWIf0r9eceXOCUeYvx3NheI2K82/Ri/mVZaW1T+jjb/aRF2JP9Yf
            fLYL2Kq/SMVx72lgsz8=
        epsilon: 0.1
        eta0: 0.01
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            0WuUHCBWDEA=
        l1_ratio: 0.5
        learning_rate: invscaling
        loss: huber
        max_iter: 1000
        n_iter: null
        n_iter_: 1000
        penalty: elasticnet
        power_t: 0.25
        random_state: null
        shuffle: true
        t_: 518001.0
        tol: null
        verbose: 0
        warm_start: false
      sigma_sphere:
        C: 1.0
        _max_iter: 1000
        _tol: null
        alpha: 0.01
        average: false
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [17]
          - *id002
          - false
          - !!binary |
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
        epsilon: 0.01
        eta0: 0.01
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            myr8yBjCqD8=
        l1_ratio: 0.5
        learning_rate: invscaling
        loss: huber
        max_iter: 1000
        n_iter: null
        n_iter_: 1000
        penalty: elasticnet
        power_t: 0.25
        random_state: null
        shuffle: true
        t_: 745001.0
        tol: null
        verbose: 0
        warm_start: false
  - - accuracy
    - r0_sphere: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        pw1KWw2Pwj8=
      rg_gp: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        eS267MGDzT8=
      sigma_sphere: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        Zj48HYm85D8=
