!!python/object/apply:collections.OrderedDict
- - - version
    - [0, 19, 1]
  - - scalers
    - diffraction_peaks:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - &id001 !!python/name:numpy.ndarray ''
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - &id002 !!python/object/apply:numpy.dtype
            args: [f8, 0, 1]
            state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
          - false
          - !!binary |
            6hz5jxCaN0Ck39Lgt1n4P2YTtOTsIHY/2b3ZibowNEBdw+UbX5QKQHKjN9g6Rbo/BiBsuBmWYD/n
            vjWivBjAP9J1QpTGz9y/cRNToiIj4L908KVSQnbbv7fiFMYi796/NHhWO+bH4D8=
        n_samples_seen_: 1784
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            pr9zixVZNUDrOQTLfnDnP/pkf1tapH0/bRwSV14VQUCr8cRsQCDvP6xaIAagtps/PbfTlwtCQz8+
            7hSkAOi0P6RAauxElyNAjGoNlZl6yz878ZbzGRTLPxxT1LktE8s/2xwijiIfzD8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            mEHcjch7fEChlFm9QSvhP4Pk/+QvdQs/4EzXAoU9kkCl0hhUnUbuP06GvElAAEg/PMxDKOwtlz4q
            ucqsJVF7PzeWk9fZ/FdAIEZ44biYpz+bP5Rr+OmmPz9PJKho6KY/F2XUw5q2qD8=
        with_mean: true
        with_std: true
      guinier_porod:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            6hz5jxCaN0Ck39Lgt1n4P2YTtOTsIHY/2b3ZibowNEBdw+UbX5QKQHKjN9g6Rbo/BiBsuBmWYD/n
            vjWivBjAP9J1QpTGz9y/cRNToiIj4L908KVSQnbbv7fiFMYi796/NHhWO+bH4D8=
        n_samples_seen_: 1784
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            pr9zixVZNUDrOQTLfnDnP/pkf1tapH0/bRwSV14VQUCr8cRsQCDvP6xaIAagtps/PbfTlwtCQz8+
            7hSkAOi0P6RAauxElyNAjGoNlZl6yz878ZbzGRTLPxxT1LktE8s/2xwijiIfzD8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            mEHcjch7fEChlFm9QSvhP4Pk/+QvdQs/4EzXAoU9kkCl0hhUnUbuP06GvElAAEg/PMxDKOwtlz4q
            ucqsJVF7PzeWk9fZ/FdAIEZ44biYpz+bP5Rr+OmmPz9PJKho6KY/F2XUw5q2qD8=
        with_mean: true
        with_std: true
      spherical_normal:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            6hz5jxCaN0Ck39Lgt1n4P2YTtOTsIHY/2b3ZibowNEBdw+UbX5QKQHKjN9g6Rbo/BiBsuBmWYD/n
            vjWivBjAP9J1QpTGz9y/cRNToiIj4L908KVSQnbbv7fiFMYi796/NHhWO+bH4D8=
        n_samples_seen_: 1784
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            pr9zixVZNUDrOQTLfnDnP/pkf1tapH0/bRwSV14VQUCr8cRsQCDvP6xaIAagtps/PbfTlwtCQz8+
            7hSkAOi0P6RAauxElyNAjGoNlZl6yz878ZbzGRTLPxxT1LktE8s/2xwijiIfzD8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            mEHcjch7fEChlFm9QSvhP4Pk/+QvdQs/4EzXAoU9kkCl0hhUnUbuP06GvElAAEg/PMxDKOwtlz4q
            ucqsJVF7PzeWk9fZ/FdAIEZ44biYpz+bP5Rr+OmmPz9PJKho6KY/F2XUw5q2qD8=
        with_mean: true
        with_std: true
      unidentified:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            7YLQX3HHNUBMtBfWrj74P58NFRPCKXw/EUYq2Do/M0BZOyNt+nQKQOl8mmKfR7s/8MRKQRZ0YD/F
            QTehTlXCP8qJNwnPBNi/R91tOw8U2783w1LtxznXv5vlA+htBNq/X7r9Vd8Z3D8=
        n_samples_seen_: 1946
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            y3Hbe9lRNUCjsMwX+JjnP87cpyh9foM/lF7Y0T91QEBIb7yZDbryPx/HZyhTCp8/WNb56DneQj+d
            SwN+zPG4Pykt7sSAxiJAsVip2bqg1j8qhM6IGAHUP7oGnZvSxNU/SjlhTjSF1z8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            9Euymn1ofEBvx5vev2bhP+ULojdRwBc/10gM2trtkEAU5ykWEuv1P3ZsGnMEHE4/dtAE1BBAlj6p
            y0nS1XGDP9RELnJACFZAhH8MPCgAwD83AztpvQK5P5DzNAsenr0/AsrMq6VJwT8=
        with_mean: true
        with_std: true
  - - models
    - diffraction_peaks:
        C: 1.0
        _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id002
          - false
          - !!binary |
            AAAAAAAA8D8AAAAAAADwPw==
        _max_iter: 5
        _tol: null
        alpha: 0.0001
        average: false
        class_weight: null
        classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - &id003 !!python/object/apply:numpy.dtype
            args: [i8, 0, 1]
            state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
          - false
          - !!binary |
            AAAAAAAAAAABAAAAAAAAAA==
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1, 13]
          - *id002
          - false
          - !!binary |
            CkScBeA9M0CDiZ1Wwr0UQNBXy+CP8tC/SpG/x6A6N0DjyuB9nw4YwPGVy5SB2T7AZhO730feEkAX
            CG2trMMiwK4LpAoXfwdAAAAAAAAAAAAXr5mXTKYfQFgJ3LU85wFA+1GFNG5j+T8=
        epsilon: 0.1
        eta0: 0.0
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            VHbxS+TeIUA=
        l1_ratio: 0.5
        learning_rate: optimal
        loss: log
        loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
        max_iter: null
        n_iter: null
        n_iter_: 5
        n_jobs: 1
        penalty: elasticnet
        power_t: 0.5
        random_state: null
        shuffle: true
        t_: 8921.0
        tol: null
        verbose: 0
        warm_start: false
      guinier_porod:
        C: 1.0
        _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id002
          - false
          - !!binary |
            AAAAAAAA8D8AAAAAAADwPw==
        _max_iter: 5
        _tol: null
        alpha: 0.1
        average: false
        class_weight: null
        classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id003
          - false
          - !!binary |
            AAAAAAAAAAABAAAAAAAAAA==
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1, 13]
          - *id002
          - false
          - !!binary |
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8
            SkEl5/nxPwAAAAAAAAAAAAAAAAAAAAC/1L4iwVmyvwAAAAAAAAAAAAAAAAAAAAA=
        epsilon: 0.1
        eta0: 0.0
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            3N3WebpY3r8=
        l1_ratio: 1.0
        learning_rate: optimal
        loss: log
        loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
        max_iter: null
        n_iter: null
        n_iter_: 5
        n_jobs: 1
        penalty: l1
        power_t: 0.5
        random_state: null
        shuffle: true
        t_: 8921.0
        tol: null
        verbose: 0
        warm_start: false
      spherical_normal:
        C: 1.0
        _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id002
          - false
          - !!binary |
            AAAAAAAA8D8AAAAAAADwPw==
        _max_iter: 5
        _tol: null
        alpha: 0.01
        average: false
        class_weight: null
        classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id003
          - false
          - !!binary |
            AAAAAAAAAAABAAAAAAAAAA==
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1, 13]
          - *id002
          - false
          - !!binary |
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOj0CisD8/S/AAAAAAAAAACQ
            nGGRpUsFwAAAAAAAAAAAAAAAAAAAAAAxn2SKomnfPwAAAAAAAAAAAAAAAAAAAAA=
        epsilon: 0.1
        eta0: 0.0
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            sQhjoxV7C0A=
        l1_ratio: 0
        learning_rate: optimal
        loss: log
        loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
        max_iter: null
        n_iter: null
        n_iter_: 5
        n_jobs: 1
        penalty: l1
        power_t: 0.5
        random_state: null
        shuffle: true
        t_: 8921.0
        tol: null
        verbose: 0
        warm_start: false
      unidentified:
        C: 1.0
        _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id002
          - false
          - !!binary |
            AAAAAAAA8D8AAAAAAADwPw==
        _max_iter: 5
        _tol: null
        alpha: 0.1
        average: false
        class_weight: null
        classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id003
          - false
          - !!binary |
            AAAAAAAAAAABAAAAAAAAAA==
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1, 13]
          - *id002
          - false
          - !!binary |
            g9z/Z52jwr+LCm0j3YiGP19P2RTQQdE/8GWE+/yDp78bXx9uPbuVv7d+cGPz484/cTCtSM3Nnr8n
            e5YEusvOP//rDMF4dYI/Z6enZWM71D8Tat1C3K3UP2PfLjErgtQ/CLWoWWfl078=
        epsilon: 0.1
        eta0: 0.0
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            xxFnlmlLC8A=
        l1_ratio: 0
        learning_rate: optimal
        loss: log
        loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
        max_iter: null
        n_iter: null
        n_iter_: 5
        n_jobs: 1
        penalty: l2
        power_t: 0.5
        random_state: null
        shuffle: true
        t_: 9731.0
        tol: null
        verbose: 0
        warm_start: false
  - - accuracy
    - diffraction_peaks: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        iZa3Mv1u7z8=
      guinier_porod: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        OV5BG3Vl6j8=
      spherical_normal: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        Vi54pl2y7z8=
      unidentified: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        BcyD3j2i7z8=
